Catalogo_telefonico/Controllers/AdministradorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Catalogo_telefonico.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;
using Catalogo_telefonico.Models.Enums;
using Catalogo_telefonico.Help;

namespace Catalogo_telefonico.Controllers
{
    public class AdministradorController:Controller
    {
        private readonly UserManager<SccUser> _user;
        public AdministradorController(UserManager<SccUser> user)
        {
            _user = user;
        }
        public async Task<ActionResult> Index(int pageNumber=1)
        {
            IQueryable<SccUser> users = _user.Users.Where(c=>c.UserName!=User.Identity.Name).AsQueryable();
            List<UserModel> usermodel= new List<UserModel>();
           
            foreach (SccUser user in users)
            {
                IEnumerable<string> roles = await _user.GetRolesAsync(user);
                Roles userRole = (Roles)Enum.Parse(typeof(Roles), roles.FirstOrDefault(), true);
                var userViewModel = Mapper.Map<UserModel>(user);
                user.NormalizedUserName= userRole.ToString();
                usermodel.Add(userViewModel);
            }
            IQueryable<UserModel> userModels = usermodel.ToList().AsQueryable(); 
            return View(await Paginacion<SccUser>.Create(users, pageNumber, 5));
          
        }
    }


}

Catalogo_telefonico/Controllers/AuthorizationController.cs
using Catalogo_telefonico.Models;
using Catalogo_telefonico.Models.Enums;
using Catalogo_telefonico.Models.ViewModel;
using Catalogo_telefonico.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Catalogo_telefonico.Controllers
{
    public class AuthorizationController:Controller
    {
        private readonly UserManager<SccUser> _userManager;
        private readonly SignInManager<SccUser> _signInManager;
        private readonly AuthorizationService _auth;

        public AuthorizationController(
            UserManager<SccUser> userManager,
            SignInManager<SccUser> signInManager, AuthorizationService authorization)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _auth = authorization;
           

        }
        public async Task<ActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                if (await _userManager.IsInRoleAsync(user, Roles.Administrador.ToString()))
                {
                    return RedirectToAction("Index", "Administrador");
                }
                if (await _userManager.IsInRoleAsync(user, Roles.Telefonico.ToString()) || await _userManager.IsInRoleAsync(user, Roles.supervisor.ToString()))
                {
                    return RedirectToAction("Index", "LineasMoviles");
                }
            }
            return View();
        }

        [HttpPost("login")]

        public async Task<ActionResult> login(LoginModelView login)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(login.UserName);
            var result=await _signInManager.PasswordSignInAsync(user, login.Password, false,false);
               

                if (result.Succeeded)

                {
                    if (await _userManager.IsInRoleAsync(user, Roles.Administrador.ToString()))
                    {
                        return RedirectToAction("Index", "Administrador");
                    }
                    if (await _userManager.IsInRoleAsync(user, Roles.Telefonico.ToString()) || await _userManager.IsInRoleAsync(user, Roles.supervisor.ToString()))
                    {
                        return RedirectToAction("Index", "LineasMoviles");
                    }
                }
                TempData["error"] = "Usuario o Contraseña incorrecta";

                return View();
            }
            return View(login);
          
        }
        public async Task<ActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("");
        }
    }
}

Catalogo_telefonico/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using Catalogo_telefonico.Models.Enums;
@inject SignInManager<SccUser> SignInManager
@inject UserManager<SccUser> UserManager
@{
    var isSignedIn = SignInManager.IsSignedIn(User);
    var isAdmin = false;
    var isTelefonico = false;
    var isSupervisor = false;


    if (isSignedIn)
    {
        isAdmin = User.IsInRole("administrador");
        if (!isAdmin)
        {
            isTelefonico = User.IsInRole(Roles.Telefonico.ToString());
            if (!isTelefonico)
            {
                isSupervisor = User.IsInRole(Roles.supervisor.ToString());
                if (!isSupervisor)
                {
                    isSupervisor = true;
                }
            }
        }
    }
    string controller = (string)ViewContext.RouteData.Values["controller"];
    string action = (string)ViewContext.RouteData.Values["action"];
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catalogo_telefonico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/fontawesome-free-5.14.0-web/css/all.css" rel="stylesheet" />
    <link href="~/fontawesome-free-5.14.0-web/css/solid.css" rel="stylesheet" />
    <link href="~/fontawesome-free-5.14.0-web/css/solid.min.css" rel="stylesheet" />
    <link href="~/fontawesome-free-5.14.0-web/css/fontawesome.css" rel="stylesheet" />
    <link href="~/fontawesome-free-5.14.0-web/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/fontawesome-free-5.14.0-web/css/regular.css" rel="stylesheet" />
    <link href="~/fontawesome-free-5.14.0-web/css/regular.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container body-content">
        @if (isSignedIn)
        {
            if (isAdmin)
            {
                <nav class="navbar navbar-dark bg-dark">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Authorization" asp-action="Logout"><i class="fas fa-window-close"></i> Cerrar sesion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="LineasMoviles" asp-action="Index"> <i class="fas fa-phone-square-alt"></i> Catalogo de Telefono</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Administrador" asp-action="Index"><i class="fas fa-users"></i> Catalogo de Usuarios</a>
                        </li>
                        <li class="nav-item float-right">
                            <a class=" nav-link text-white"><i class="fas fa-hand-holding"></i> Hola @UserManager.GetUserName(User)!</a>
                        </li>
                    </ul>
                </nav>
            }
            if (isSupervisor || isTelefonico)
            {
                <nav class="navbar navbar-dark bg-dark">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Authorization" asp-action="Logout"><i class="fas fa-window-close"></i> Cerrar sesion</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="LineasMoviles" asp-action="Index"><i class="fas fa-phone-square-alt"></i> Catalogo de Telefono</a>
                        </li>
                        <li class="nav-item float-right">
                            <a class=" nav-link text-white"><i class="fas fa-hand-lizard"></i> Hola @UserManager.GetUserName(User)!</a>
                        </li>
                    </ul>
                </nav>
            }
        }
        else
        {
            <nav class="navbar navbar-dark bg-dark">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Authorization" asp-action="Login"><i class="fas fa-phone-alt"></i> Acceder a tus lineas telefonicas</a>
                    </li>
                </ul>
            </nav>
        }

        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/d6c73f321f.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
    <script src="~/fontawesome-free-5.14.0-web/js/all.js"></script>
    <script src="~/fontawesome-free-5.14.0-web/js/fontawesome.js"></script>
    <script src="~/fontawesome-free-5.14.0-web/js/fontawesome.min.js"></script>
    <script src="~/fontawesome-free-5.14.0-web/js/regular.js"></script>
    <script src="~/fontawesome-free-5.14.0-web/js/regular.min.js"></script>
    <script src="~/fontawesome-free-5.14.0-web/js/solid.js"></script>
    <script src="~/fontawesome-free-5.14.0-web/js/solid.min.js"></script>
</body>
</html>